// Cloudflare Worker — passcode-gated preview server.
//
// Routes:
//   GET  /sites/{websiteId}                — landing; cookie OR ?p=<passcode>; passcode form on miss
//   POST /sites/{websiteId}                — passcode form submit
//   GET  /sites/{websiteId}/<asset path>   — same passcode rule, OR ?op=<token>
//   GET  /screenshots/{websiteId}/{size}.png — same passcode rule
//   GET  /healthz                          — always 200
//
// Auth model:
//   - Passcode (8-char Crockford-Base32) is generated by the publisher Lambda (iter 5.3),
//     stored as argon2id hash in Workers KV under `passcode:<websiteId>`.
//   - On submit, validate by fetching the hash and constant-time-comparing.
//     This iter (0.D) ships a SHA-256-with-salt validator as scaffolding; iter 5.4
//     swaps in argon2id (see passcode.ts TODO).
//   - On success, set a HMAC-SHA256-signed cookie scoped to /sites/<websiteId>/.
//   - Operator bypass (iter 5.5): a short-lived `?op=<token>` signed by the
//     screenshot Lambda lets the Browser Rendering headless browser render the
//     preview without the passcode form. Still subject to revocation. See
//     passcode.ts § OPERATOR BYPASS TOKEN.
//
// Rate limiting is at the Cloudflare zone level (terraform-managed ruleset),
// not in Worker code. The Worker assumes hot requests have already been blocked.

import { validatePasscode, signCookie, verifyCookie, verifyOpToken, COOKIE_NAME } from "./passcode";

export interface Env {
  PREVIEWS: R2Bucket;
  PREVIEW_PASSCODES_KV: KVNamespace;
  PASSCODE_SALT: string;
  ENVIRONMENT: string;
}

export default {
  async fetch(request: Request, env: Env, _ctx: ExecutionContext): Promise<Response> {
    return withDefaultHeaders(await route(request, env));
  },
} satisfies ExportedHandler<Env>;

async function route(request: Request, env: Env): Promise<Response> {
  const url = new URL(request.url);
  const path = url.pathname;

  if (path === "/healthz") {
    return new Response("OK", { status: 200, headers: { "content-type": "text/plain" } });
  }

  const sitesMatch = /^\/sites\/([a-z0-9_-]+)(?:\/(.*))?$/.exec(path);
  if (sitesMatch) {
    const websiteId = sitesMatch[1];
    const assetPath = sitesMatch[2] ?? "";

    if (request.method === "POST") {
      return handlePasscodeSubmit(request, env, websiteId, url);
    }
    return serveAsset(request, env, websiteId, assetPath);
  }

  // `desktop` / `mobile` are the sizes the screenshotter Lambda (iter 5.5)
  // actually writes per 02-data-model.md § Website.screenshots; the legacy
  // thumb/small/medium/large names from 0.D.2 are kept for compatibility.
  const screenshotMatch =
    /^\/screenshots\/([a-z0-9_-]+)\/(thumb|small|medium|large|desktop|mobile)\.png$/.exec(path);
  if (screenshotMatch) {
    return serveScreenshot(request, env, screenshotMatch[1], screenshotMatch[2]);
  }

  return new Response("Not Found", { status: 404 });
}

// Quality rule (10-quality-rules.md § Rule 2): every response from the preview
// Worker must carry `X-Robots-Tag: noindex, nofollow` so search engines never
// index passcode-gated content even if a URL leaks. Applied uniformly here so
// no individual route can forget.
function withDefaultHeaders(res: Response): Response {
  const headers = new Headers(res.headers);
  if (!headers.has("x-robots-tag")) headers.set("x-robots-tag", "noindex, nofollow");
  return new Response(res.body, { status: res.status, statusText: res.statusText, headers });
}

async function serveAsset(
  request: Request,
  env: Env,
  websiteId: string,
  assetPath: string,
): Promise<Response> {
  const url = new URL(request.url);
  const cookie = request.headers.get("cookie") ?? "";
  const queryPasscode = url.searchParams.get("p");
  const opToken = url.searchParams.get("op");

  // Operator bypass: a valid short-lived ?op= token (minted by the screenshot
  // Lambda) renders the preview for the headless browser without the passcode
  // form. We also set the normal signed cookie so any same-origin sub-resource
  // fetches the browser makes authenticate too (the current sitebundle is
  // self-contained, but the cookie future-proofs split assets). Still gated on
  // revocation so the bypass can't outlive a revoked preview.
  if (opToken && (await verifyOpToken(opToken, websiteId, env.PASSCODE_SALT))) {
    if (!(await passcodeStillIssued(env, websiteId))) {
      return passcodeFormResponse(websiteId, "This preview has been revoked.");
    }
    return serveStoredAsset(env, websiteId, assetPath, await signCookie(websiteId, env.PASSCODE_SALT));
  }

  const cookieValid = await verifyCookie(cookie, websiteId, env.PASSCODE_SALT);
  if (!cookieValid) {
    if (queryPasscode) {
      const ok = await checkPasscode(env, websiteId, queryPasscode);
      if (ok) {
        const setCookie = await signCookie(websiteId, env.PASSCODE_SALT);
        // Redirect to the same path WITHOUT the ?p= so the URL doesn't leak the cleartext passcode.
        const cleanUrl = new URL(request.url);
        cleanUrl.searchParams.delete("p");
        return new Response(null, {
          status: 303,
          headers: {
            location: cleanUrl.toString(),
            "set-cookie": setCookie,
          },
        });
      }
    }
    return passcodeFormResponse(websiteId);
  }

  // Cookie valid → check the passcode is still issued before serving.
  // Closes the revocation-propagation gap: a deleted KV entry blocks
  // access within REVOCATION_TTL_SECONDS (60s) even when a valid
  // signed cookie is presented. Without this check, cookies remained
  // valid for their full 24h TTL after revocation.
  if (!(await passcodeStillIssued(env, websiteId))) {
    return passcodeFormResponse(websiteId, "This preview has been revoked.");
  }

  return serveStoredAsset(env, websiteId, assetPath);
}

// serveStoredAsset fetches the preview document/asset from R2 and returns it.
// Callers must have already authorized the request (valid cookie, valid ?p=,
// or valid ?op= token) and confirmed the passcode is still issued.
async function serveStoredAsset(
  env: Env,
  websiteId: string,
  assetPath: string,
  setCookie?: string,
): Promise<Response> {
  const objectKey = assetPath ? `sites/${websiteId}/${assetPath}` : `sites/${websiteId}/index.html`;
  const obj = await env.PREVIEWS.get(objectKey);
  if (!obj) {
    return new Response("Not Found", { status: 404 });
  }

  const headers = new Headers();
  obj.writeHttpMetadata(headers);
  headers.set("etag", obj.httpEtag);
  headers.set("cache-control", "private, max-age=300");
  if (setCookie) headers.set("set-cookie", setCookie);
  return new Response(obj.body, { headers });
}

async function serveScreenshot(
  request: Request,
  env: Env,
  websiteId: string,
  size: string,
): Promise<Response> {
  const cookieValid = await verifyCookie(request.headers.get("cookie") ?? "", websiteId, env.PASSCODE_SALT);
  if (!cookieValid) {
    return new Response("Forbidden", { status: 403 });
  }
  // Revocation check (see serveAsset for rationale).
  if (!(await passcodeStillIssued(env, websiteId))) {
    return new Response("Forbidden", { status: 403 });
  }
  const obj = await env.PREVIEWS.get(`screenshots/${websiteId}/${size}.png`);
  if (!obj) {
    return new Response("Not Found", { status: 404 });
  }
  const headers = new Headers();
  obj.writeHttpMetadata(headers);
  headers.set("content-type", "image/png");
  headers.set("cache-control", "private, max-age=300");
  return new Response(obj.body, { headers });
}

async function handlePasscodeSubmit(
  request: Request,
  env: Env,
  websiteId: string,
  url: URL,
): Promise<Response> {
  const form = await request.formData();
  const submitted = form.get("passcode");
  if (typeof submitted !== "string" || submitted.length === 0) {
    return passcodeFormResponse(websiteId, "Enter a passcode.");
  }

  const ok = await checkPasscode(env, websiteId, submitted);
  if (!ok) {
    return passcodeFormResponse(websiteId, "Incorrect passcode.");
  }

  const setCookie = await signCookie(websiteId, env.PASSCODE_SALT);
  return new Response(null, {
    status: 303,
    headers: {
      location: `${url.origin}/sites/${websiteId}/`,
      "set-cookie": setCookie,
    },
  });
}

async function checkPasscode(env: Env, websiteId: string, submitted: string): Promise<boolean> {
  const stored = await env.PREVIEW_PASSCODES_KV.get(`passcode:${websiteId}`);
  if (!stored) return false;
  return validatePasscode(submitted, stored, env.PASSCODE_SALT);
}

// Revocation propagation knob. KV reads are cheap but not free; cache
// the "passcode still issued" check per-website at the isolate level
// so a hot preview pays one KV read per REVOCATION_TTL_SECONDS, not
// one per request.
const REVOCATION_TTL_SECONDS = 60;
const revocationCache = new Map<string, { expiresAt: number; issued: boolean }>();

// passcodeStillIssued returns true if the KV namespace currently has a
// hash entry for this websiteId. A missing entry (operator revocation
// via the Cloudflare API, or by Worker.Delete from a future regen
// flow) flips this to false within REVOCATION_TTL_SECONDS at the
// isolate level — and instantly on cold isolates.
//
// Per-isolate cache is good enough: Cloudflare warm isolates are
// scoped per-region per-cold-start; even a hot website doing 100 RPS
// won't keep more than one regional isolate hot for more than a few
// minutes. The 60s cache bounds the propagation lag everywhere.
export async function passcodeStillIssued(env: Env, websiteId: string): Promise<boolean> {
  const now = Date.now() / 1000;
  const cached = revocationCache.get(websiteId);
  if (cached && cached.expiresAt > now) {
    return cached.issued;
  }
  const stored = await env.PREVIEW_PASSCODES_KV.get(`passcode:${websiteId}`);
  const issued = stored !== null && stored !== "";
  revocationCache.set(websiteId, { expiresAt: now + REVOCATION_TTL_SECONDS, issued });
  return issued;
}

// resetRevocationCacheForTests clears the in-memory cache between
// tests so KV-state changes are observed deterministically. Exported
// only via the source file; tests import directly.
export function resetRevocationCacheForTests(): void {
  revocationCache.clear();
}

function passcodeFormResponse(websiteId: string, error?: string): Response {
  const html = `<!doctype html>
<html lang="en"><head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>Preview access — passcode required</title>
<style>
  body { font: 16px/1.5 system-ui, -apple-system, sans-serif; max-width: 28rem; margin: 4rem auto; padding: 0 1rem; color: #111; }
  form { display: flex; flex-direction: column; gap: 0.75rem; margin-top: 1rem; }
  input[name=passcode] { font: inherit; padding: 0.5rem; border: 1px solid #888; border-radius: 4px; }
  button { font: inherit; padding: 0.5rem; cursor: pointer; background: #111; color: #fff; border: 0; border-radius: 4px; }
  .error { color: #b00020; font-weight: 500; }
</style></head><body>
<h1>This preview is private</h1>
<p>Enter the 8-character passcode you received in your invitation email.</p>
${error ? `<p class="error">${escapeHtml(error)}</p>` : ""}
<form method="POST" action="/sites/${escapeHtml(websiteId)}" autocomplete="off">
  <input type="text" name="passcode" required autocapitalize="characters" pattern="[A-Z0-9]{8}" maxlength="8" />
  <button type="submit">View preview</button>
</form>
<p style="margin-top:2rem;font-size:0.875rem;color:#666;">If you didn't receive an email, please contact the sender.</p>
</body></html>`;
  return new Response(html, {
    status: 200,
    headers: {
      "content-type": "text/html; charset=utf-8",
      "cache-control": "no-store",
    },
  });
}

function escapeHtml(s: string): string {
  return s.replace(
    /[&<>"']/g,
    (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[c]!,
  );
}

// COOKIE_NAME is exported for tests but not used at runtime here; suppress unused-import lint.
void COOKIE_NAME;
