// Package bedrock implements InvokeStructured[T] — the only allowed way to
// call Anthropic models on Bedrock from this project. Per
// .ralph/specs/stdlib/json-output-conventions.md, every Bedrock call uses
// tool-use for structured output (free-text JSON parsing is forbidden), is
// gated by pkg/cost.WithCostCap semantics, and caches its result keyed on
// (promptID, sha256(input)).
//
// Schema validation is delegated through the Validator interface; the
// concrete JSON-Schema validator lives in pkg/schemas (iter 0.E.6) and is
// wired at Lambda startup via SetValidator. Until then the default no-op
// validator accepts any payload — useful for unit tests, never for prod.
package bedrock

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"sync"
	"time"

	"github.com/aws/aws-sdk-go-v2/aws"
	awsconfig "github.com/aws/aws-sdk-go-v2/config"
	"github.com/aws/aws-sdk-go-v2/feature/dynamodb/attributevalue"
	"github.com/aws/aws-sdk-go-v2/service/bedrockruntime"
	"github.com/aws/aws-sdk-go-v2/service/dynamodb"
	dtypes "github.com/aws/aws-sdk-go-v2/service/dynamodb/types"

	"github.com/reaandrew/ai-website-agency/lambdas/pkg/cost"
	"github.com/reaandrew/ai-website-agency/lambdas/pkg/ddb"
)

// Stage matches the cost-ledger stage names. Use the constants below; the
// string is what shows up in `pipeline.<stage>.*` metrics and the cost ledger.
type Stage string

const (
	StageAudit          Stage = "audit"
	StageSpec           Stage = "spec"
	StageEmail          Stage = "email"
	StageTunerStyle     Stage = "tuner-style"
	StageTunerEmailTone Stage = "tuner-email-tone"
	StageTunerTargeting Stage = "tuner-targeting"
)

// CacheTypePrefix is written to the `type` attribute of cache rows.
const CacheTypePrefix = "BedrockCache"

// DefaultCacheTTL applies when InvokeInput.CacheTTL is zero. 30 days matches
// the lambdas/CLAUDE.md rule "Bedrock outputs cached in DynamoDB with
// expires_at (TTL-enabled); cache key includes prompt version."
const DefaultCacheTTL = 30 * 24 * time.Hour

// DefaultTemperature is used when InvokeInput.Temperature is nil. Specs and
// emails benefit from low randomness per stdlib convention #3.
const DefaultTemperature = 0.2

// AnthropicVersion is the bedrock-2023-05-31 wire-format header required on
// every Anthropic-on-Bedrock invocation. Required by Bedrock; doesn't change
// when the model changes.
const AnthropicVersion = "bedrock-2023-05-31"

// ErrNoToolUse is returned when Bedrock didn't include the requested tool_use
// block in its response. The handler should DLQ this event.
var ErrNoToolUse = errors.New("bedrock: response missing required tool_use")

// Message is one user/assistant turn passed to Bedrock.
type Message struct {
	Role    string `json:"role"`    // "user" | "assistant"
	Content string `json:"content"` // for now, plain-text content; widen to []block when needed
}

// InvokeInput is the per-call input to InvokeStructured. T is the Go type the
// tool_use payload unmarshals into; ToolSchema is the matching JSON Schema
// (typically generated by pkg/schemas.JSONSchemaFor[T]).
type InvokeInput[T any] struct {
	ModelID     string          // e.g. ModelHaiku45
	PromptID    string          // versioned prompt ID, e.g. "spec.v1"
	System      string          // system prompt
	Messages    []Message       // user/assistant turns
	ToolName    string          // forced tool name, e.g. "produceSpec"
	ToolSchema  json.RawMessage // input_schema for the tool — Validator runs against this
	Stage       Stage           // for cost ledger + metrics
	EstimateUSD float64         // pre-call cost estimate (Assert against CapUSD)
	CapUSD      float64         // 0 disables the cap check (testing only)
	CacheKey    string          // sha256(promptID + input-hash); use CacheKey() helper
	CacheTTL    time.Duration   // 0 = DefaultCacheTTL (30d)
	MaxTokens   int             // required; no global default
	Temperature *float64        // nil = DefaultTemperature (0.2)
}

// API is the subset of *bedrockruntime.Client we depend on. Tests inject a
// fake; production lazily builds the real client on first Client() call.
type API interface {
	InvokeModel(ctx context.Context, in *bedrockruntime.InvokeModelInput, opts ...func(*bedrockruntime.Options)) (*bedrockruntime.InvokeModelOutput, error)
}

var (
	clientMu sync.RWMutex
	client   API
)

// Client returns the package-level Bedrock client, lazily constructed on
// first use. Override in tests with SetClient.
func Client(ctx context.Context) (API, error) {
	clientMu.RLock()
	c := client
	clientMu.RUnlock()
	if c != nil {
		return c, nil
	}
	cfg, err := awsconfig.LoadDefaultConfig(ctx)
	if err != nil {
		return nil, fmt.Errorf("bedrock: loading AWS config: %w", err)
	}
	clientMu.Lock()
	defer clientMu.Unlock()
	if client == nil {
		client = bedrockruntime.NewFromConfig(cfg)
	}
	return client, nil
}

// SetClient overrides the cached client. Pass nil to clear. For tests.
func SetClient(c API) {
	clientMu.Lock()
	client = c
	clientMu.Unlock()
}

// CacheKey builds the canonical cache key for a (promptID, inputHash) pair.
// inputHash is the SHA-256 of the canonical JSON of the prompt's structural
// inputs (system, messages, tool name+schema). Helper kept here so callers
// don't reinvent it.
func CacheKey(promptID, inputHash string) string {
	h := sha256.Sum256([]byte(promptID + ":" + inputHash))
	return hex.EncodeToString(h[:])
}

// InvokeStructured runs the full pipeline:
//  1. Cache hit on (promptID, cacheKey) → return cached T.
//  2. cost.Assert(stage, estimate, cap) — bail with ErrBudgetCapExceeded.
//  3. Build the InvokeModel body (forced tool_use).
//  4. Call Bedrock.
//  5. Extract tool_use(name=ToolName).input.
//  6. Validator.Validate(schema, payload) — DLQ on failure.
//  7. Unmarshal into T.
//  8. cost.Record(stage, actualUsd from token usage).
//  9. Cache T with expires_at = now + CacheTTL.
//
// Step 8 records the post-call usd (computed from token usage) rather than
// the estimate so token-billed calls are billed honestly.
func InvokeStructured[T any](ctx context.Context, in InvokeInput[T]) (T, error) {
	var zero T

	if in.ModelID == "" || in.PromptID == "" || in.ToolName == "" || in.MaxTokens <= 0 {
		return zero, errors.New("bedrock: ModelID, PromptID, ToolName, MaxTokens are required")
	}

	if cached, ok, err := getCached[T](ctx, in.PromptID, in.CacheKey); err != nil {
		return zero, err
	} else if ok {
		return cached, nil
	}

	if err := cost.Assert(ctx, string(in.Stage), in.EstimateUSD, in.CapUSD); err != nil {
		return zero, err
	}

	body, err := buildBody(in)
	if err != nil {
		return zero, fmt.Errorf("bedrock: building body: %w", err)
	}

	bc, err := Client(ctx)
	if err != nil {
		return zero, err
	}
	res, err := bc.InvokeModel(ctx, &bedrockruntime.InvokeModelInput{
		ModelId:     aws.String(in.ModelID),
		Body:        body,
		ContentType: aws.String("application/json"),
		Accept:      aws.String("application/json"),
	})
	if err != nil {
		return zero, fmt.Errorf("bedrock: invoke %s: %w", in.PromptID, err)
	}

	toolInput, usage, err := extractToolUse(res.Body, in.ToolName)
	if err != nil {
		return zero, fmt.Errorf("bedrock: %s: %w", in.PromptID, err)
	}

	if err := currentValidator().Validate(in.ToolSchema, toolInput); err != nil {
		return zero, fmt.Errorf("bedrock: %s: tool input failed schema: %w", in.PromptID, err)
	}

	var out T
	if err := json.Unmarshal(toolInput, &out); err != nil {
		return zero, fmt.Errorf("bedrock: %s: unmarshalling tool input: %w", in.PromptID, err)
	}

	usd := ComputeUSD(in.ModelID, usage.InputTokens, usage.OutputTokens)
	if err := cost.Record(ctx, string(in.Stage), usd); err != nil {
		return zero, fmt.Errorf("bedrock: recording spend: %w", err)
	}

	if err := setCached(ctx, in.PromptID, in.CacheKey, toolInput, in.CacheTTL); err != nil {
		return zero, fmt.Errorf("bedrock: caching response: %w", err)
	}

	return out, nil
}

// buildBody serialises an Anthropic-on-Bedrock invocation that forces
// tool_use of the named tool. Forces low temperature and tool_choice = tool.
func buildBody[T any](in InvokeInput[T]) ([]byte, error) {
	temp := DefaultTemperature
	if in.Temperature != nil {
		temp = *in.Temperature
	}
	var toolSchema any = json.RawMessage(`{}`)
	if len(in.ToolSchema) > 0 {
		toolSchema = in.ToolSchema
	}
	return json.Marshal(map[string]any{
		"anthropic_version": AnthropicVersion,
		"max_tokens":        in.MaxTokens,
		"temperature":       temp,
		"top_p":             0.9,
		"system":            in.System,
		"messages":          in.Messages,
		"tools": []map[string]any{{
			"name":         in.ToolName,
			"description":  "Single allowed output channel.",
			"input_schema": toolSchema,
		}},
		"tool_choice": map[string]any{
			"type": "tool",
			"name": in.ToolName,
		},
	})
}

// usageBlock is the token-count envelope every Anthropic Bedrock response
// carries.
type usageBlock struct {
	InputTokens  int `json:"input_tokens"`
	OutputTokens int `json:"output_tokens"`
}

// extractToolUse parses a Bedrock-on-Anthropic response body, finds the
// tool_use block named toolName, and returns its input + usage. If the
// expected tool_use block is absent, returns ErrNoToolUse.
func extractToolUse(body []byte, toolName string) (json.RawMessage, usageBlock, error) {
	var resp struct {
		Content []struct {
			Type  string          `json:"type"`
			Name  string          `json:"name"`
			Input json.RawMessage `json:"input"`
		} `json:"content"`
		Usage usageBlock `json:"usage"`
	}
	if err := json.Unmarshal(body, &resp); err != nil {
		return nil, usageBlock{}, fmt.Errorf("parsing response: %w", err)
	}
	for _, c := range resp.Content {
		if c.Type == "tool_use" && c.Name == toolName {
			return c.Input, resp.Usage, nil
		}
	}
	return nil, resp.Usage, ErrNoToolUse
}

// --- cache helpers --------------------------------------------------------

// cacheRecord is the items-table shape for cached Bedrock outputs. Payload is
// stored as a JSON string (DDB attribute type S) so it round-trips cleanly
// without the SDK trying to base64-encode a json.RawMessage as binary.
type cacheRecord struct {
	PK        string `dynamodbav:"pk"`
	SK        string `dynamodbav:"sk"`
	Type      string `dynamodbav:"type"`
	PromptID  string `dynamodbav:"promptId"`
	CacheKey  string `dynamodbav:"cacheKey"`
	Payload   string `dynamodbav:"payload"`
	CreatedAt string `dynamodbav:"createdAt"`
	ExpiresAt int64  `dynamodbav:"expires_at"`
}

func cachePK(promptID string) string   { return "CACHE#BEDROCK#" + promptID }
func cacheSK(cacheKey string) string   { return "KEY#" + cacheKey }
func cacheType(promptID string) string { return CacheTypePrefix + "#" + promptID }

// nowFunc is overridable in tests.
var nowFunc = func() time.Time { return time.Now().UTC() }

// getCached looks up a previous response for (promptID, cacheKey). Returns
// (zero, false, nil) when there is no row; (value, true, nil) on a hit.
// Empty cacheKey disables caching (skipped without DDB call).
func getCached[T any](ctx context.Context, promptID, cacheKey string) (T, bool, error) {
	var zero T
	if promptID == "" || cacheKey == "" {
		return zero, false, nil
	}
	dc, err := ddb.Client(ctx)
	if err != nil {
		return zero, false, fmt.Errorf("getting DynamoDB client: %w", err)
	}
	table := ddb.TableName()
	if table == "" {
		return zero, false, errors.New("ITEMS_TABLE is not set")
	}
	out, err := dc.GetItem(ctx, &dynamodb.GetItemInput{
		TableName: aws.String(table),
		Key: map[string]dtypes.AttributeValue{
			"pk": &dtypes.AttributeValueMemberS{Value: cachePK(promptID)},
			"sk": &dtypes.AttributeValueMemberS{Value: cacheSK(cacheKey)},
		},
	})
	if err != nil {
		return zero, false, fmt.Errorf("GetItem: %w", err)
	}
	if len(out.Item) == 0 {
		return zero, false, nil
	}
	var rec cacheRecord
	if err := attributevalue.UnmarshalMap(out.Item, &rec); err != nil {
		return zero, false, fmt.Errorf("unmarshalling cache record: %w", err)
	}
	if err := json.Unmarshal([]byte(rec.Payload), &zero); err != nil {
		return zero, false, fmt.Errorf("unmarshalling cached payload: %w", err)
	}
	return zero, true, nil
}

// setCached stores a response payload at (promptID, cacheKey) with TTL.
// Empty cacheKey is a no-op (matches the spec's "cache key includes prompt
// version" rule — callers without a key skip the cache).
func setCached(ctx context.Context, promptID, cacheKey string, payload json.RawMessage, ttl time.Duration) error {
	if promptID == "" || cacheKey == "" {
		return nil
	}
	if ttl == 0 {
		ttl = DefaultCacheTTL
	}
	dc, err := ddb.Client(ctx)
	if err != nil {
		return fmt.Errorf("getting DynamoDB client: %w", err)
	}
	table := ddb.TableName()
	if table == "" {
		return errors.New("ITEMS_TABLE is not set")
	}
	now := nowFunc()
	rec := cacheRecord{
		PK:        cachePK(promptID),
		SK:        cacheSK(cacheKey),
		Type:      cacheType(promptID),
		PromptID:  promptID,
		CacheKey:  cacheKey,
		Payload:   string(payload),
		CreatedAt: now.Format(time.RFC3339),
		ExpiresAt: now.Add(ttl).Unix(),
	}
	item, err := attributevalue.MarshalMap(rec)
	if err != nil {
		return fmt.Errorf("marshalling cache record: %w", err)
	}
	_, err = dc.PutItem(ctx, &dynamodb.PutItemInput{
		TableName: aws.String(table),
		Item:      item,
	})
	if err != nil {
		return fmt.Errorf("PutItem: %w", err)
	}
	return nil
}
